ERROR:root:Restore failed!!!
Traceback (most recent call last):
  File "./db_restore.py", line 88, in main
    restore(databases, restore_day, store, user, password, host)
  File "./db_restore.py", line 48, in restore
    loggin.worning()
NameError: global name 'loggin' is not defined
